excel:
  file: cases.xlsx

logger:
  name: "test"
  logfile: "log_tem.txt"
  logger_level: "DEBUG"
  stream_level: "DEBUG"
  file_level: "INFO"

db_mysql:
  host: "test.senguo.me"
  port: 3306
  user: "test"
  password: "senguo_mysql"
  charset: 'utf8'

db_redis:
  host: "test.senguo.me"
  port: "6379"
  auth: "senguo_redis"

db_mongo:
  host:
  port:


user:
  mobile_phone: "17386049001"
  password: "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"

host: http://pftest.senguo.me
